version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    registries:
      - fontawesome-pro
registries:
  fontawesome-pro:
    type: npm-registry
    url: https://npm.fontawesome.com/
    token: ${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}
