version: "3.9"

name: "sphincz-website-prod"

services:
  backend:
    image: "ghcr.io/sphincz/sphincz-website-backend:latest"
    ports:
      - "8090:8090"
    env_file:
      - ./.env
    environment:
      - CGO_ENABLED=1
    volumes:
      - "./pb_data:/data"

  frontend:
    image: "ghcr.io/sphincz/sphincz-website-frontend:latest"
    ports:
      - "3000:80"
    depends_on:
      - backend
    env_file:
      - ./.env
    environment:
      - VITE_API_ADDRESS=http://merda:8090
      - VITE_TURNSTILE_KEY=${VITE_TURNSTILE_KEY}
      - TURNSTILE_SECRET=${TURNSTILE_SECRET}
      - NODE_ENV=production