version: "3.9"

name: "sphincz-website-dev"

services:
  backend:
    container_name: "sphincz-website-backend-dev"
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8090:8090"
    volumes:
      - ./pb_data:/data                # Mount data directory for persistent data
      - ./migrations:/app/migrations   # Mount migrations directory for live updates
      - ./internal:/app/internal       # Mount internal code for live updates
      - ./main.go:/app/main.go         # Explicitly mount Go source files for live updates
    environment:
      - CGO_ENABLED=1

  frontend:
    container_name: "sphincz-website-frontend-dev"
    build:
      context: ./frontend
      dockerfile: Dockerfile   # Use the new frontend Dockerfile
    volumes:
      - ./frontend:/app    # Mount the frontend source for live updates
      - /app/node_modules  # Avoid overriding node_modules
    ports:
      - "3000:3000"  # Expose port 3000 for the frontend
    environment:
      - VITE_API_ADDRESS=http://localhost:8090
      - NODE_ENV=development
    command: npm run dev  # Start the dev server with hot reloading