name: Deploy

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
      url:
        type: string
    secrets:
      infra-ssh-key:
        required: true

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    concurrency: ${{ inputs.environment }}
    environment:
      name: ${{ inputs.environment }}
      url: ${{ inputs.url }}
    steps:
      - name: Checkout home-ops
        uses: actions/checkout@v4
        with:
          repository: gabe565/home-ops
          path: home-ops
          ssh-key: ${{ secrets.infra-ssh-key }}

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Setup yampl
        uses: clevyr/setup-yampl-action@v1

      - name: Update backend
        run: |
          yampl --inplace \
            --value tag="${GITHUB_REF_NAME#v}" \
            home-ops/kubernetes/apps/portfolio/app/helmrelease.yaml

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        if: inputs.environment == 'prod'
        with:
          repository: home-ops
          file_pattern: kubernetes/kubernetes/apps/portfolio/app/helmrelease.yaml
          commit_message: "chore(portfolio): Update image tag to ${{ github.ref_name }}"
